autobidsportal/routes.py
"""All routes in the portal are defined here."""
from __future__ import annotations

import tempfile
import uuid
from datetime import datetime
from json import dumps, loads
from pathlib import Path
from typing import NoReturn

import flask_excel as excel
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required, login_user, logout_user
from sqlalchemy import desc
from werkzeug.urls import url_parse
from werkzeug.wrappers.response import Response

from autobidsportal.datalad import (
    RiaDataset,
    delete_all_content,
    delete_tar_file,
    rename_tar_file,
)
from autobidsportal.dateutils import TIME_ZONE
from autobidsportal.dcm4cheutils import Dcm4cheError
from autobidsportal.dicom import get_study_records
from autobidsportal.email import send_email
from autobidsportal.forms import (
    AccessForm,
    BidsForm,
    ExcludeScansForm,
    ExplicitCfmm2tarForm,
    GenResetForm,
    IncludeScansForm,
    LoginForm,
    RegistrationForm,
    RemoveAccessForm,
    ResetPasswordForm,
    StudyConfigForm,
    Tar2bidsRunForm,
)
from autobidsportal.models import (
    Cfmm2tarOutput,
    DataladDataset,
    DatasetType,
    ExplicitPatient,
    Principal,
    Study,
    Task,
    User,
    db,
)
from autobidsportal.ssh import remove_zip_files

portal_blueprint = Blueprint(
    "portal_blueprint",
    __name__,
    template_folder="templates",
)


def check_current_authorized(study: Study):
    """Check that the current_user is authorized to view this study.

    Parameters
    ----------
    study
        Study to check for user authorization
    """
    if (not current_user.admin) and (  # pyright: ignore
        current_user not in study.users_authorized
    ):
        abort(404)


@portal_blueprint.route("/", methods=["GET"])
@portal_blueprint.route("/index", methods=["GET"])
def index() -> str:
    """Render a splash page to describe autobids.

    Returns
    -------
    str
        Rendered path for homepage / index.html
    """
    return render_template("index.html")


@portal_blueprint.route("/getting-started", methods=["GET"])
def getting_started() -> str:
    """Render a page with getting started instructions.

    Returns
    -------
    str
        Rendered path for getting staged page
    """
    return render_template("getting_started.html")


@portal_blueprint.route("/new", methods=["GET", "POST"])
def new_study() -> str | Response:
    """Provide users with a survey form to fill (new study page).

    If the Principal table is not empty, the principal names are added to
    the principal dropdown in the form. Submitter information and their
    answer is added to the database.

    Returns
    -------
    str | Response
        Rendered path to survey or refresh page if valid submission of form
    """
    form = BidsForm()
    principal_names = [
        (p.principal_name, p.principal_name)
        for p in db.session.query(Principal).all()  # pyright: ignore
    ]
    form.principal.choices = principal_names
    form.principal.choices.insert(0, ("Other", "Other"))

    if form.validate_on_submit():
        study = form.gen_study()
        db.session.add(study)  # pyright: ignore
        db.session.commit()  # pyright: ignore

        flash(
            "Thanks, the survey has been submitted! "
            "If you haven't already, please add 'bidsdump' as an authorized user to "
            "your study on the CFMM DICOM server.",
        )
        send_email(
            "New study request",
            (
                f"A new request has been submitted by {form.name.data}"
                f" ({form.email.data}). ID: {study.id}"
            ),
            additional_recipients=[
                admin.email for admin in User.query.filter_by(admin=True).all()
            ],
        )

        return redirect(url_for("portal_blueprint.new_study"))
    return render_template("survey.html", form=form)


@portal_blueprint.route("/login", methods=["GET", "POST"])
def login() -> str | Response:
    """User login page.

    Returns
    -------
    str | Response
        Rendered home page is user is authenticated or credentials valid,
        login page if invalid credentials or login page if user not logged in
    """
    if current_user.is_authenticated:  # pyright: ignore
        return redirect(url_for("portal_blueprint.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid email or password")
            return redirect(url_for("portal_blueprint.login"))

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get("next")
        if (not next_page) or url_parse(next_page).netloc:
            next_page = url_for("portal_blueprint.index")

        return redirect(next_page)
    return render_template("login.html", title="Sign In", form=form)


@portal_blueprint.route("/register", methods=["GET", "POST"])
def register() -> str | Response:
    """User registration page.

    Returns
    -------
    str | Response
        Rendered registration page, or if user successfully registers, they
        are redirected to the login page
    """
    if current_user.is_authenticated:  # pyright: ignore
        return redirect(url_for("portal_blueprint.index"))
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, admin=False)  # pyright: ignore
        user.set_password(form.password.data)

        db.session.add(user)  # pyright: ignore
        db.session.commit()  # pyright: ignore
        current_app.logger.info("New user %i registered.", user.id)
        flash("Congratulations, you are now a registered user!")

        return redirect(url_for("portal_blueprint.login"))
    return render_template("register.html", title="Register", form=form)


@portal_blueprint.route("/reset", methods=["GET", "POST"])
def gen_reset() -> str:
    """Generate a workflow to reset a user's password.

    Returns
    -------
    str
        Rendered page for user to reset their password
    """
    form = GenResetForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).one_or_none()
        exists = False
        # If email is found to be associated with a user
        if user is not None:
            for key in current_app.redis.scan_iter(  # pyright: ignore
                match="reset_*",
            ):
                # If there is ongoing process within reset time frame
                if current_app.redis.get(key) == email:  # pyright: ignore
                    exists = True
                    current_app.logger.info(
                        "Found existing key for user %s. Key: %s.",
                        email,
                        key,
                    )
                    break
            # If no ongoing process, send user email with unique reset URL
            if not exists:
                uuid_reset = str(uuid.uuid4())
                key_reset = f"reset_{uuid_reset}"
                current_app.redis.set(  # pyright: ignore
                    key_reset,
                    email,
                    ex=10 * 60,
                )
                current_app.logger.info(
                    "Generated reset url for user %s. UUID: %s",
                    user.email,
                    uuid_reset,
                )
                root_url = current_app.config["ROOT_URL"]
                sub_url = url_for(
                    "portal_blueprint.reset_password",
                    uuid_reset=uuid_reset,
                )
                send_email(
                    "Autobids password reset",
                    (
                        "Please visit the following link to reset your "
                        "password. The link will expire in ten minutes.\n\n"
                        f"{root_url}{sub_url}\n\n"
                        "Ignore this email if it has been sent in error."
                    ),
                    additional_recipients=[email],
                )
        # No users are found associated with provided email
        else:
            current_app.logger.info(
                "Attempted reset for nonassociated email %s ignored.",
                email,
            )
        flash(
            "An email with further instructions has been sent if the "
            "provided email is associated with a user account.",
        )
    return render_template("gen_reset.html", form=form)


@portal_blueprint.route("/reset/<uuid_reset>", methods=["GET", "POST"])
def reset_password(uuid_reset: str) -> str | Response:
    """Reset a user's password, given a workflow has started.

    Parameters
    ----------
    uuid_reset
        Key associated with unique reset process

    Returns
    -------
    str | Response
        Renders reset password page, or redirects user to regenerate reset
        password URL
    """
    # Check if reset key is valid
    key_reset = f"reset_{uuid_reset}"
    if current_app.redis.exists(key_reset) < 1:  # pyright: ignore
        flash(
            "The reset password link is incorrect or has expired. Please "
            "resubmit your password reset request.",
        )
        return redirect(url_for("portal_blueprint.gen_reset"))

    form = ResetPasswordForm()
    email = current_app.redis.get(key_reset)  # pyright: ignore
    # If no user is found by email
    if (user := User.query.filter_by(email=email).one_or_none()) is None:
        flash(
            "This password reset link encountered an unexpected error. "
            "Please resubmit your password reset request.",
        )
        current_app.redis.delete(key_reset)  # pyright: ignore

autobidsportal/templates/admin.html
<!-- Main admin page -->
{% extends "base.html" %}
{% block title %}
  Admin
{% endblock title %}
{% block
  app_content %}
  <div class="container">
    <div class="row my-3">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <!-- User table -->
            <h3 class="card-title">Users</h3>
            <table class="table table-light caption-top">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Admin</th>
                  <th scope="col">Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Has access to the following studies</th>
                </tr>
              </thead>
              <tbody>
                {% for u in users %}
                  <tr>
                    <td>
                      <a class="btn btn-primary"
                         href="{{ url_for('portal_blueprint.admin', user_id=u.id) }}"
                         role="button">View more</a>
                    </td>
                    <td>
                      {% if u.admin==True %}
                        Yes
                      {% else %}
                        No
                      {% endif %}
                    </td>
                    <td>{{ u.email }}</td>
                    <td>{{ u.email }}</td>
                    <td>
                      {% for a in u.access_to %}
                        <div>{{ a.desc.replace(' ', '^') }}</div>
                      {% endfor %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- Storage locations -->
    <div class="row my-3">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Storage Locations</h3>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                RIA (Tar files and BIDS datasets in DataLad):
                <code>{{ ria_url }}</code>
              </li>
              <li class="list-group-item">
                BIDS dataset archives: <code>{{ archive_url }}</code>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock app_content %}

autobidsportal/templates/administration.html
{% extends "base.html" %}
{% block title %}
  User {{ user.email }}
{% endblock
title %}
{% block app_content %}
  <div class="container">
    <div class="row my-3">
      <div class="col">
        <table class="table table-light">
          <tr>
            <th scope="col">Administrator</th>
            <th scope="col">Email</th>
            <th scope="col">Access to which studies?</th>
            <th scope="col">Grant access to the following studies?</th>
            <th scope="col">Remove access to the following studies?</th>
          </tr>
          <tr>
            <td>
              <!-- Toggle admin privileges -->
              {% if user.admin == True %}
                <div>Yes</div>
                <br />
                <form id="form"
                      method="post"
                      action="{{ url_for('portal_blueprint.admin', user_id=user.id) }}">
                  <button class="btn btn-primary" type="submit" name="admin" value="False">
                    Remove Admin
                  </button>
                </form>
              {% else %}
                <div>No</div>
                <br />
                <form id="form"
                      method="post"
                      action="{{ url_for('portal_blueprint.admin', user_id=user.id) }}">
                  <button class="btn btn-primary" type="submit" name="admin" value="True">
                    Make Admin
                  </button>
                </form>
              {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <!-- Available studies -->
            <td>
              {% for study in user.studies %}
                <div>{{ study.principal }}^{{ study.project_name }}</div>
              {% endfor %}
            </td>
            <!-- Studies to grant access -->
            <td>
              <form id="survey-form"
                    method="post"
                    action="{{ url_for('portal_blueprint.admin', user_id=user.id) }}">
                <fieldset class="form-group">
                  {{ form.csrf_token }}
                  {% for choice in form.choices %}
                    <div class="form-check">
                      {{ choice(class="form-check-input") }} {{ choice.label(class="form-check-label") }}
                    </div>
                  {% endfor %}
                </fieldset>
                <br />
                <input type="submit" name=access-{{ user.id }} value="Grant Access" class="btn btn-primary" {% if user.admin %}disabled="disabled"{% endif %} />
              </form>
            </td>
            <!-- Studies to remove access -->
            <td>
              <form id="survey-form"
                    method="post"
                    action="{{ url_for('portal_blueprint.admin', user_id=user.id) }}">
                <fieldset class="form-group">
                  {{ removal_form.csrf_token }}
                  {% for choice in
                    removal_form.choices_to_remove %}
                    {% if choice not in
                      user.studies %}
                      <div class="form-check">
                        {{ choice(class="form-check-input") }} {{ choice.label(class="form-check-label") }}
                      </div>
                    {% endif %}
                  {% endfor %}
                </fieldset>
                <br />
                <!-- If admin, disallow removal of access -->
                {% if user.admin == True %}
                  <input type="submit" name=remove-{{ user.id }} value="Remove Access" class="btn btn-primary" disabled="disabled" />
                {% else %}
                  <input type="submit" name=remove-{{ user.id }} value="Remove Access" class="btn btn-primary" />
                {% endif %}
              </form>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
{% endblock app_content %}

autobidsportal/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Metadata -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width-device-width, initial-scale=1" />
    <meta name="description" content="Autobids web portal" />
    <meta name="keywords" content="bids,neuroimaging,dicom,nifti" />
    <title>
      {% block title %}
      {% endblock title %}
    - Autobids Portal</title>
    <!-- Bootstrap Core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous" />
    <!-- Custom CSS-->
    <link rel="stylesheet"
          type="text/css"
          href="{{ url_for('static',filename='styles/survey.css') }}" />
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans"
          rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-default navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <!-- Navigation toggler -->
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigation options -->
        <a class="navbar-brand" href="{{ url_for("portal_blueprint.index") }}">Home</a>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for("portal_blueprint.new_study") }}">New Study</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 href="{{ url_for("portal_blueprint.getting_started") }}">Getting Started</a>
            </li>
            <!-- Non-logged in user -->
            {% if current_user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for("portal_blueprint.login") }}">Login</a>
              </li>
            {% else %}
              <!-- Logged in user, additional admin option -->
              {% if current_user.admin == True %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for("portal_blueprint.user_list") }}">Admin</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for("portal_blueprint.results") }}">Studies</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for("portal_blueprint.logout") }}">Logout</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
      <!-- Pop-up notifications-->
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="container">
              <div class="row my-3">
                <div class="col">
                  <div class="alert alert-info" role="alert">{{ message }}</div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <!-- Main application content -->
      {% block app_content %}
      {% endblock app_content %}
      <div class="modal fade" id="autobidsModal" tabindex="-1">
        <div class="modal-dialog modal-dialog-scrollable modal-xl">
          <div class="modal-content" id="autobidsModalContent"></div>
        </div>
      </div>
    {% endblock content %}
    <!-- Bootstrap javascript -->
    {% block scripts %}
      <script type="text/javascript" src={{url_for("static", filename="lib/autobids-react/dist/index.js") }}></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
              integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
              crossorigin="anonymous"></script>
    {% endblock scripts %}
  </body>
</html>

autobidsportal/templates/dicom_error.html
{% extends "base.html" %}
{% block title %}
  DICOM Error
{% endblock title %}
{% block app_content %}
  <div class="container">
    <div class="row my-3">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">{{ err }}</h1>
            <p class="card-text">{{ err_cause }}</p>
            <a class="card-link" href="{{ url_for("portal_blueprint.results") }}">Back</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock app_content %}

autobidsportal/templates/getting_started.html
<!-- Home page -->
{% extends "base.html" %}
{% block title %}
  Home
{% endblock title %}
{% block
  app_content %}
  <div class="container">
    <!-- Getting started -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h1 class="card-title">Getting started!</h1>
            <p class="card-text">
              This page provides some information to help you get started with autobids,
              detailing the steps taken to convert data acquired from a CFMM scanner to
              a <a href="https://bids.neuroimaging.io/" target="_blank" rel="noopener">BIDS</a>
              dataset.
            </p>
            <p class="card-text">
              If you haven't already, please
              <a href="{{ url_for("portal_blueprint.register") }}"
                 target="_blank"
                 rel="noopener">create an account</a> in order to interact with and
              manage your study.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- New study -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h2 class="card-title">New study</h2>
            <p class="card-text">
              After you have acquired some data from a CFMM scanner, a request can be
              made for autobids conversion:
              <ol type="1">
                <li>
                  Request a new study from the
                  <a href="{{ url_for("portal_blueprint.new_study") }}">"New Study"</a>
                  tab.
                </li>
                <li>
                  Have the PI (or study manager) add "bidsdump" as an authorized user
                  for the study on the CFMM DICOM server. A step-by-step guide can be found
                  <a href="https://github.com/khanlab/autobids/wiki/Granting-access-to-bidsdump"
                     target="_blank"
                     rel="noopener">here</a>.
                </li>
                <li>
                  Sign up for a <a href="https://app.globus.org/" target="_blank" rel="noopener">Globus</a>
                  in order to download the converted data.
                </li>
              </ol>
              An admin will review the new study, enable it, and grant you access if
              there are no issues. Additional users can be granted access to the study.
              For autobids to work on the study, the "Active" option needs to be checked
              in the study config.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Cfmm2tar -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h2 class="card-title">DICOM retrieval</h2>
            <p class="card-text">
              <em>
                (This step makes use of
                <a href="https://github.com/khanlab/cfmm2tar"
                   target="_blank"
                   rel="noopener">cfmm2tar</a>)
              </em>
            </p>
            <p class="card-text">
              The first step of autobids queries the CFMM DICOM server for study data
              based on information that was provided when creating a new study.
              For each newly acquired scan that is found, a tarball file will be
              created containing all of the associated DICOMS for a given participant.
              This tarball file will be named based on a combination of values pulled
              from the DICOM server and autobids database (which will be created if it
              can't be found):
              <br>
              <br>
              <code>PI_ProjectDescription_ScanDate_PatientName_StudyID.Hash.tar</code>
            </p>
            <p class="card-text">
              All created tarballs can be found under the "Tar Files" table within a given
              study. It is important that these tarballs are named consistently as
              these names are used to organize the data in the next step. The easiest
              way to ensure this is to have a consistent patient naming patterns when
              acquiring the data. If renaming is necessary, it can be done by clicking
              the "Rename" button for each tarball.
            </p>
            <p class="card-text">
              <!-- Individual subjects -->
              If you wish to manage individual participants (e.g. exclude from
              conversion), you can do so by querying the DICOM server via autobids by
              clicking "All matching scans" on the study page.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Tar2bids -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h2 class="card-title">BIDS-ify data</h2>
            <p class="card-text">
              <em>
                (This step makes use of
                <a href="https://github.com/khanlab/tar2bids"
                   target="_blank"
                   rel="noopener">tar2bids</a>)
              </em>
            </p>
            <p class="card-text">
              The next step of autobids uses the previously created tarballs and custom
              heuristics to map the DICOMS to NifTIs organized according to BIDS. There
              are two important settings under the study's config page:
              <ol>
                <li>
                  Heuristic - study specific mapping of DICOM values (to add or update
                  an existing heuristic, create a pull request to the
                  <a href="https://github.com/khanlab/tar2bids-heuristics"
                     target="_blank"
                     rel="noopener">heuristics repository</a>)
                </li>
                <li>
                  Tar2bids Patient Name Search String - extraction of patient names
                  and session labels (if necessary)
                </li>
              </ol>
              After the data has been converted, it will be validated according to the
              BIDS specification. Any errors or warnings will appear here! If the files
              you converted are not part of the specification, you can add the pattern
              to the .bidsignore content under the study configuration to exclude them
              from validation.
            </p>
            <p class="card-text">
              If the study was acquired on the 7T scanner, distortion correction is
              automatically performed on the converted data after validation.
              Additionally, optional defacing can be performed by checking
              the option under the study config.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Archiving -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h2 class="card-title">Accessing the data</h2>
            <p class="card-text">
              Ensure a globus identity has been granted access to the study under the
              study config, as converted data is archived and shared via globus. Note
              the study id, which will be in the name of the shared globus collection.
              In each collection, one zip archive will be created containing the
              converted data since the last time tar2bids has been run.
            </p>
            <p class="card-text">
              Instructions for accessing the converted data can be found in the study
              page.
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Notes -->
    <div class="row">
      <div class="col">
        <div class="card my-3">
          <div class="card-body">
            <h2 class="card-title">Notes</h2>
            <p class="card-text">
              <li>
                For any questions concerning autobids, please post them on the
                <a href="https://cbs-discourse.uwo.ca" target="_blank" rel="noopener">
                  CBS Discourse
                </a>.
              </li>
              <li>
                Each step noted is automatically run throughout the day,
                but can also be triggered manually
              </li>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock app_content %}

autobidsportal/templates/login.html
{% extends "base.html" %}
{% block title %}
  Login
{% endblock title %}
{% block app_content %}
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <form id="login-form" action="" method="post">
          {{ form.csrf_token }}
          <div class="card my-3">
            <div class="card-body">
              <h1>Sign In</h1>
              <!-- Sign in form -->
              {{ form.email.label }}
              {{ form.email(class="form-control") }}
              {{ form.password.label }}
              {{ form.password(class="form-control") }}
              <!-- Remember me checkbox -->
              <div class="form-check">
                {{ form.remember_me(class="form-check-input") }}
                <label class="form-check-label">Remember Me</label>
              </div>
              <br />
              {{ form.submit(class="btn btn-primary") }}
              <br />
              <!-- Registraton / forgot password options -->
              <p>
                New User? <a class="download" href="{{ url_for("portal_blueprint.register") }}">Click to Register!</a>
              </p>
              <p>
                <a href="{{ url_for("portal_blueprint.gen_reset") }}">
                  Forgot your password?
                </a>
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock app_content %}